# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c18987ec094553364afa43dab5ebeef653d1bd2c1335664dfbc7a706e09d697c01acfa87fc8178ea67db2ae2aca816c0bed2f9c6050dc1222f3288161126cd6e

test:
  secret_key_base: 2d9eaffe135e813f4b9507b7aa49a8713ba28ac5cceb2ab6f3c433f4046d7f70b078352e87ed167ed496c5d1e157bf89cb0c46cdcc0b2a102fdcbc9ba185a1ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
